language: node_js
node_js:
  - "7"
before_deploy:
  - pip install --user awscli
  - npm run build
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync --sse --acl public-read dist/ s3://jamesbrill.co.uk
  skip_cleanup: true
  on:
    branch: master
